package clases;
// Generated 24-feb-2020 14:12:24 by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer codAlumno;
     private Profesor profesor;
     private String nombre;
     private String apellido;
     private String dni;

    public Alumno() {
    }

    public Alumno(Profesor profesor, String nombre, String apellido, String dni) {
       this.profesor = profesor;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
    }
   
    public Integer getCodAlumno() {
        return this.codAlumno;
    }
    
    public void setCodAlumno(Integer codAlumno) {
        this.codAlumno = codAlumno;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }




}


