package clases;
// Generated 24-feb-2020 14:12:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer codProfe;
     private Clase clase;
     private String nombre;
     private String apellido;
     private String dni;
     private Set alumnos = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(Clase clase, String nombre, String apellido, String dni) {
        this.clase = clase;
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
    }
    public Profesor(Clase clase, String nombre, String apellido, String dni, Set alumnos) {
       this.clase = clase;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.alumnos = alumnos;
    }
   
    public Integer getCodProfe() {
        return this.codProfe;
    }
    
    public void setCodProfe(Integer codProfe) {
        this.codProfe = codProfe;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


